packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.6.0'
  - '@storybook/addon-vitest@10.6.0'
  - '@storybook/builder-vite@10.6.0'
  - '@storybook/react-dom-shim@10.6.0'
  - '@storybook/react-vite@10.6.0'
  - '@storybook/react@10.6.0'
  - storybook@10.6.0
