#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const src = join(root, "src");
const dist = join(root, "dist");

const primitives = JSON.parse(readFileSync(join(src, "primitives.json"), "utf8"));

const THEMES = [
  { name: "light", selector: ":root", file: "semantic.light.json" },
  { name: "dark", selector: '[data-theme="dark"]', file: "semantic.dark.json" },
  { name: "high-contrast", selector: '[data-theme="high-contrast"]', file: "semantic.high-contrast.json" },
];

function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/\s+/g, "-").toLowerCase();
}

function flatten(obj, prefix, out, inheritedType) {
  const type = obj.$type ?? inheritedType;
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;
    const name = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && "$value" in value) {
      out[name] = { $type: value.$type ?? type, $value: value.$value };
    } else if (value && typeof value === "object") {
      flatten(value, name, out, type);
    }
  }
  return out;
}

function resolveRef(ref, lookup, stack = new Set()) {
  if (!(ref in lookup)) throw new Error(`Unresolved token reference: ${ref} (chain: ${[...stack].join(" -> ") || "root"})`);
  if (stack.has(ref)) throw new Error(`Circular token reference: ${[...stack, ref].join(" -> ")}`);
  const { $value, $type } = lookup[ref];
  if (typeof $value === "string" && $value.includes("{")) {
    return substitute($value, lookup, new Set([...stack, ref]));
  }
  return { $value, $type };
}

function substitute(value, lookup, stack) {
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const resolved = resolveRef(ref.trim(), lookup, stack);
    return resolved.$value;
  });
}

const primitiveTokens = flatten(primitives, "", {}, undefined);
const primitiveLookup = primitiveTokens;

// Primitive tokens emit as --yp-<domain>-<...>
function cssVarName(name) {
  return `--yp-${name.split(".").map(kebab).join("-")}`;
}

function block(selector, lines) {
  return `${selector} {\n${lines.join("\n")}\n}`;
}

const header =
  "/* Generated by @yarapa-ui/tokens build. Source of truth: src/*.json. Do not edit by hand. */";

const baseLines = ["", "/* Primitives */"];
for (const [name, def] of Object.entries(primitiveTokens)) {
  const type = def.$type ? ` /* ${def.$type} */` : "";
  baseLines.push(`  ${cssVarName(name)}: ${def.$value};${type}`);
}

const resolved = {};
const themeBlocks = {};
for (const theme of THEMES) {
  const semantic = JSON.parse(readFileSync(join(src, theme.file), "utf8"));
  const tokens = flatten(semantic, "", {}, undefined);
  const lookup = { ...primitiveLookup, ...tokens };
  const lines = [``, `/* Semantic tokens — ${theme.name} */`];
  const themeResolved = {};
  for (const [name, def] of Object.entries(tokens)) {
    const value = resolveRef(name, lookup);
    themeResolved[name] = { ...def, $value: value.$value ?? value, resolved: value.$value ?? value };
    lines.push(`  ${cssVarName(name)}: ${value.$value ?? value};`);
  }
  resolved[theme.name] = themeResolved;
  themeBlocks[theme.name] = block(theme.selector, lines);
}

// The reduced-motion and forced-colors guards stay in the base artifact so
// every consumer gets them regardless of which theme file they load.
const baseCss = [
  header,
  block(":root", baseLines),
  themeBlocks.light,
  `/* Users with reduced-motion get near-instant transitions regardless of theme. */`,
  `@media (prefers-reduced-motion: reduce) {`,
  `  :root, [data-theme="dark"], [data-theme="high-contrast"] {`,
  `    --yp-motion-fast: 0ms;`,
  `    --yp-motion-base: 0ms;`,
  `    --yp-motion-slow: 0ms;`,
  `  }`,
  `}`,
  ``,
  `/* Forced-colors mode: keep structure legible, let the UA remap colors. */`,
  `@media (forced-colors: active) {`,
  `  :root, [data-theme="dark"], [data-theme="high-contrast"] {`,
  `    --yp-color-border-default: CanvasText;`,
  `    --yp-color-border-strong: CanvasText;`,
  `    --yp-color-border-focus: Highlight;`,
  `    --yp-color-brand-solid: ButtonText;`,
  `    --yp-color-brand-solid-text: ButtonFace;`,
  `    --yp-shadow-sm: none;`,
  `    --yp-shadow-md: none;`,
  `    --yp-shadow-lg: none;`,
  `    --yp-shadow-overlay: none;`,
  `  }`,
  `}`,
].join("\n");

mkdirSync(join(dist, "themes"), { recursive: true });
writeFileSync(join(dist, "tokens.css"), baseCss + "\n");
writeFileSync(join(dist, "themes", "dark.css"), `${header}\n${themeBlocks.dark}\n`);
writeFileSync(join(dist, "themes", "high-contrast.css"), `${header}\n${themeBlocks["high-contrast"]}\n`);
writeFileSync(
  join(dist, "tokens.json"),
  JSON.stringify({ primitives: primitiveTokens, semantic: resolved }, null, 2) + "\n",
);
console.log(
  `@yarapa-ui/tokens: wrote ${Object.keys(primitiveTokens).length} primitives + ` +
    `${Object.values(resolved).map((t) => Object.keys(t).length).join("/")} semantic tokens ` +
    `-> dist/tokens.css + dist/themes/*.css + dist/tokens.json`,
);
